### ISSUE TITLE
Need Nav Local to link to tabs

### ISSUE THREAD

**Issue by deepalikamble** [CenturyLinkCloud/Cyclops#102]
Implemented Nav local navigation but unable to link it to the Tab contents. Please suggest.

**Comment by osbornm** [comment]
the tabs we have are just styles there is no "functionality" same with the local nav so it would be dependent on the framework you are using... 

One approach would be to use links that refer to sections of the page (has links) and use javascript in hide or show the correct content and highlight the tab eg `/currentpage.html#tab1`. But again this is out of the scope of the functionality that cyclops provides.

**Comment by deepalikamble** [comment]
Thanks for the prompt reply. This helps will try.

Thanks and Regards,
Deepali Kamble
