### ISSUE TITLE
Jquery Version compatiblity issue when using with JQX Grid

### ISSUE THREAD

**Issue by Chethandc2014** [CenturyLinkCloud/Cyclops#103]
We are facing Jquery version issues when using Cyclops with JQX grid. Where JQX grid need JQuery version <=2.1.3. What is the minimum version of Jquery library that Cyclops supports?.

**Comment by osbornm** [comment]
For cyclops 1.7.0 the minimum supported version of jQuery is 2.1.4. The key word is supported, we do not test with any older version of jQuery so I can't say that we support them, However off the top of my head I do not know any reason why it wouldn't work. The caveat being that if you find something that is not support we aren't going to fix it :)
