### ISSUE TITLE
Not able to insert pie chart

### ISSUE THREAD

**Issue by deepalikamble** [CenturyLinkCloud/Cyclops#104]
My pie chart doesn't come up. Below is the HTML and JS I have written. Included Chartmin as well but still doesn't work.

Please suggest.

HTML:
<div id="panel-1-data" class="card-block panel-collapse collapse in" role="tabpanel">
						    <div id="pieChartExample"></div>
	      				  	<p class="text-center">pie chart</p>
      				  </div>

js:
	  var pieData = {
		      series: [
		        {
		            value: 300,
		            name: "Widget"
		        },
		        {
		            value: 50,
		            name: "Gizmo"
		        },
		        {
		            value: 100,
		            name: "Snarfblat"
		        },
		        {
		            value: 100,
		            name: "Dinglehopper"
		        },
		        {
		            value: 100,
		            name: "Watchamacallit"
		        },
		        {
		            value: 100,
		            name: "Doohicky"
		        }
		      ]
		    };
	  
	  $('.pieChartExample').chart({type: 'Pie', data: pieData, chartOptions: {}})

**Comment by deepalikamble** [comment]
Can I have some update on this?

**Comment by osbornm** [comment]
Sorry for the delay but it was a holiday week for the US and all of our team was on vacation.

did you include the required chartjs script? http://assets.ctl.io/cyclops/1.7.0/charts.html

**Comment by deepalikamble** [comment]
Yes I have included below

<script src="https://cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script>

Thanks and Regards,
Deepali Kamble

**Comment by deepalikamble** [comment]
PFA files. SM.html is the main html where I have included chartist.js and in dashboard .html I want the charts to render.

Thanks and Regards,
Deepali Kamble

**Comment by osbornm** [comment]
@deepalikamble it seems like you may have tried to attach files in an email reply that doesn't work. You'll have to go to the github ui

**Comment by osbornm** [comment]
Closing this issues as I have not heard anything back and not got any repro steps.
