### ISSUE TITLE
Dropdown not closing when item clicked

### ISSUE THREAD

**Issue by guyaparker** [CenturyLinkCloud/Cyclops#107]
I notice in 1.7.0 that when I click a link in a dropdown the dropdown no longer closes.

Change that causes this is https://github.com/CenturyLinkCloud/Cyclops/commit/0e7dd7b688ef8a8afc417287db2417a3620d251d

Compare clicking a link in the dropdowns in the 2 example pages:

- In http://assets.ctl.io/cyclops/1.6.0/buttons.html#dropdowns clicking a dropdown link takes you to the top of the page and when you scroll back down to the dropdown it is closed.

- In http://assets.ctl.io/cyclops/1.7.0/buttons.html#dropdowns clicking a dropdown link takes you to the top of the page and when you scroll back down to the dropdown it is still open.

Is this intentional behavior now?

Thanks

**Comment by osbornm** [comment]
Yes this was intentional, Links should take the user away from the page or cause some navigation. If they preform an action a button should be used instead.
