### ISSUE TITLE
dateTimePicker displays invalid hour range of 01-24, no 00

### ISSUE THREAD

**Issue by eknarf** [CenturyLinkCloud/Cyclops#108]
RDBS uses the atlas/cyclops "dateTimePicker" for database restores to a specific point-in-time.  The cyclops/atlas dateTimePicker only contains values 01-24 for "hour", the 24 being an invalid hour value and offering no "00" option.  FYI the minute drop-down correctly represents 00-59.

As discussed with Matt, "24"="00", however the issue remains 24 is an invalid hour value by any standard & therefore is very confusing for clients at a critical time (database restore) when preciseness & clarity are paramount.

Clients will likely be wondering if they should decrement each hour (whereby 05 actually is 04, etc) due to the given value range of 01-24... or if indeed 24=00, should that technically fall under the next day's hour range?

**Comment by jsmecham** [comment]
How silly of us. I have PR #119 pending review that should fix this.

**Comment by jsmecham** [comment]
This is fixed and should go out in 1.8.1.
