### ISSUE TITLE
Charts

### ISSUE THREAD

**Issue by lundstrt** [CenturyLinkCloud/Cyclops#109]
Hi, Do you have any plans to add more charts?  Looking for the ability to drill into a date range -- like one of these:   [fusioncharts-zoom](http://www.fusioncharts.com/features/zooming-and-scrolling/) or [highchart-stockchart](http://www.highcharts.com/stock/demo/basic-line).  Apologies if you already have--may have missed.  Thanks Tom Lundstrom (CTL - denver)

**Comment by osbornm** [comment]
No we don't have any plans for more charts. The idea we had was that we would include the basic charts most people would need and then if anyone needs more complex chart they could just use the color scheme we provide http://assets.ctl.io/cyclops/1.7.0/charts.html#chartColors
