### ISSUE TITLE
Inline confirm not working

### ISSUE THREAD

**Issue by deepalikamble** [CenturyLinkCloud/Cyclops#110]
Below is the HTML that I have written for inline confirm button
<button class="btn btn-danger btn-primary btn-icon" style="padding-left: 5px; margin-top: 0px; outline-color: white;" ng-click="removeFlag(flag.SM_REQ_NOTIFICATION_ID,flag.SM_REQ_NOTIFY_TYPE,reqDetailInfo.CORRELATION_ID);">
						  <svg xmlns="http://www.w3.org/2000/svg" class="cyclops-icon" aria-hidden="true"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-times" /></svg>
						  <span class="sr-only">remove</span></button>

Below is the js that I have added to my controller

$('.btn-danger').inlineConfirm();

Inline confirm through Jquery is not working. Please reply ASAP, its urgent.

**Comment by jsmecham** [comment]
Where are you calling the `$('.btn-danger').inlineConfirm();` code from? Is it in the click handler (i.e. `ng-click`) or is it after the view is loaded?

**Comment by deepalikamble** [comment]
its not on ng-click. its on my controller init.

**Comment by jsmecham** [comment]
To clarify, the confirmation message does not appear or it does appear and doesn't allow it to be confirmed?

**Comment by deepalikamble** [comment]
it does not appear at all. click on remove icon just deleted the record. Is placing it inside init of controller the correct place to place the inlineconfirm?

**Comment by jsmecham** [comment]
I'm not sure in the case of Angular, but most likely it needs to be called after the template has been rendered in the browser. That may not be in the controller init, but something later in the pipeline.

**Comment by jsmecham** [comment]
This may be relevant: http://gsferreira.com/archive/2015/03/angularjs-after-render-directive

**Comment by osbornm** [comment]
Sounds like the code above is executing before the button is rendered. to confirm this you can just do something like `console.log($('.btn-danger').length) the line before and if it says 0 in the console that's the case...

**Comment by deepalikamble** [comment]
trying out the after render directive

**Comment by deepalikamble** [comment]
So if that works, I wanted to be able to change the text on the message like change "Are you sure?" to "Are you sure you want to remove the flag?" something like this, so how can that be achieved?

**Comment by osbornm** [comment]
http://assets.ctl.io/cyclops/1.7.0/widgets.html#inlineConfirm

**Comment by deepalikamble** [comment]
now I am getting the Are you sure and No button but yes button is not seen text color is being set white. Is there a way to set style for yes button?

**Comment by deepalikamble** [comment]
now I am getting the Are you sure and No button but yes button is not seen text color is being set white. Is there a way to set style for yes button?

Thanks and Regards,
Deepali Kamble

**Comment by osbornm** [comment]
As stated in the documentation for ]inline confirm](http://assets.ctl.io/cyclops/1.7.0/widgets.html#inlineConfirm) the style of the "yes" button is based on the style of the original button. Please read through the documentation and look at the examples we have. If you are still unable to figure it out please reopen this issue with appropriate repro steps and code.
