### ISSUE TITLE
Full color icons

### ISSUE THREAD

**Issue by guyaparker** [CenturyLinkCloud/Cyclops#113]
I am being asked to switch from using the single color icons included in Cyclops for Windows and Linux (#icon-windows and #icon-linux) to icons that use the standard colors defined by the vendor.

Additionally we have a need for a Solaris icon.

Are these something that could be added into the Cyclops icon set?

**Comment by mattnickles** [comment]
Closing - I created three colored SVGs for @guyaparker to meet the DCC requirement. If there's further demand we can explore a colored vendor icon set in a future release. Thanks Guy!
