### ISSUE TITLE
Allow slider control to use a configurable step value

### ISSUE THREAD

**Issue by guyaparker** [CenturyLinkCloud/Cyclops#115]
With reference to the issue #30 that I created and was closed based on "won't fix, hasn't been an issue."

This has again come up as a requirement for an application I am tasked to deliver and would like you to reconsider.

**Comment by jsmecham** [comment]
Moving forward we will be using the standard `<input type="range">` with style customizations. I don't have a timeline at the moment as to when this will happen, but I don't think it makes sense to update the existing Knockout control when it's going to be rewritten to use the standard range control.

What do you think, @pascualin?

**Comment by pascualin** [comment]
I agree with @jsmecham, however I think we need to study the urgency of this features and consider releasing a minor update to support it if needed, since it will take some time to release version 2.0.0

**Comment by jsmecham** [comment]
I've gone ahead and started work to add this functionality. Take a look at https://github.com/CenturyLinkCloud/Cyclops/pull/121 for progress.

**Comment by jsmecham** [comment]
This should go out with the 1.8.2 release.
