### ISSUE TITLE
Allow control of color used in donut charts

### ISSUE THREAD

**Issue by guyaparker** [CenturyLinkCloud/Cyclops#116]
The donut charts would typically be used as a gauge where it would be good to have control of the chart color. This would allow (for instance) the gauge to change from green to yellow to red based on value being shown.

**Comment by jsmecham** [comment]
Since Cyclops just uses [Chartis](https://gionkunz.github.io/chartist-js/) you should be able to pass a new color option into the donut chart to Chartist.

**Comment by jsmecham** [comment]
More specifically, it looks like Chartist simply uses CSS to control the coloring. You could override the CSS for your usage based on the value thresholds. See https://gionkunz.github.io/chartist-js/getting-started.html#customizing-the-default-css for more info.

**Comment by guyaparker** [comment]
Thanks! If it helps others you need to over ride:

html.cyclops .ct-chart .ct-series-j .ct-slice-donut { stroke: #color; }
