### ISSUE TITLE
Icon buttons with a disabled attribute show a color block when hovered over.

### ISSUE THREAD

**Issue by guyaparker** [CenturyLinkCloud/Cyclops#123]
Icon buttons with a disabled attribute show a color block that matches the icon fill color when the button is hovered over.

See attached screenshot showing disabled attribute inserted into standard example page using firebug.

![screen shot 2017-03-14 at 09 56 20](https://cloud.githubusercontent.com/assets/11406058/23897546/86ef7bd6-08a5-11e7-87a0-65e22dce4706.png)

**Comment by pascualin** [comment]
Will be fixed on next release
