### ISSUE TITLE
The action bar active class has been deemphasized too much in latest Cyclops style update

### ISSUE THREAD

**Issue by guyaparker** [CenturyLinkCloud/Cyclops#131]
The action bar active class has been deemphasized too much in latest Cyclops style update.

The example at "http://assets.ctl.io/cyclops/1.8.2/components.html#actionToolbarActiveButton" works because all non-active actions have been disabled. This will likely not always be the case. For instance clicking the action may open a slide-well under the action bar where the active class will give an indication of context.

Would like to see a future update improve the style applied to the active class.

As a suggested starting point for a appropriate style the DCC UI will use an over ride:

`
html.cyclops .action-toolbar > li a.active,
html.cyclops .action-toolbar-left > li a.active,
html.cyclops .action-toolbar-right > li a.active,
html.cyclops .action-toolbar > li button.active,
html.cyclops .action-toolbar-left > li button.active,
html.cyclops .action-toolbar-right > li button.active,
html.cyclops .action-toolbar > li a:active,
html.cyclops .action-toolbar-left > li a:active,
html.cyclops .action-toolbar-right > li a:active,
html.cyclops .action-toolbar > li button:active,
html.cyclops .action-toolbar-left > li button:active,
html.cyclops .action-toolbar-right > li button:active {
  background-color: #e0e0e0;
  color: #3cac30;
}
html.cyclops .action-toolbar > li a.active svg.cyclops-icon,
html.cyclops .action-toolbar-left > li a.active svg.cyclops-icon,
html.cyclops .action-toolbar-right > li a.active svg.cyclops-icon,
html.cyclops .action-toolbar > li button.active svg.cyclops-icon,
html.cyclops .action-toolbar-left > li button.active svg.cyclops-icon,
html.cyclops .action-toolbar-right > li button.active svg.cyclops-icon,
html.cyclops .action-toolbar > li a:active svg.cyclops-icon,
html.cyclops .action-toolbar-left > li a:active svg.cyclops-icon,
html.cyclops .action-toolbar-right > li a:active svg.cyclops-icon,
html.cyclops .action-toolbar > li button:active svg.cyclops-icon,
html.cyclops .action-toolbar-left > li button:active svg.cyclops-icon,
html.cyclops .action-toolbar-right > li button:active svg.cyclops-icon {
  fill: #3cac30;
}
html.cyclops .action-toolbar-left>li a.active:enabled:hover svg.cyclops-icon,
html.cyclops .action-toolbar-left>li button.active:enabled:hover svg.cyclops-icon,
html.cyclops .action-toolbar-right>li a.active:enabled:hover svg.cyclops-icon,
html.cyclops .action-toolbar-right>li button.active:enabled:hover svg.cyclops-icon,
html.cyclops .action-toolbar>li a.active:enabled:hover svg.cyclops-icon,
html.cyclops .action-toolbar>li button.active:enabled:hover svg.cyclops-icon {
  fill: #3cac30;
}
`

Using standard cyclops style (delete is active):
![screen shot 2017-03-21 at 14 23 37](https://cloud.githubusercontent.com/assets/11406058/24151919/018c66fa-0e42-11e7-871b-016e946148a0.png)

Using over ride style (delete is active):
![screen shot 2017-03-21 at 14 22 49](https://cloud.githubusercontent.com/assets/11406058/24151940/0c688ba8-0e42-11e7-8eb4-cf3ba851b9c3.png)

**Comment by pascualin** [comment]
@mattnickles Could you please take a look at this and provide a design update for the active style if needed?

**Comment by mattnickles** [comment]
@pascualin Let's change the button background color to #d5d5d5 and the text and svg to #333 on active. We should also carry over this active style to ".tree-in-pane .tree-item.selected" for consistency.

**Comment by pascualin** [comment]
Thank you @mattnickles. I was working on the updates but when I set the actionToolbar item to active I already get the specified styles:

![image](https://cloud.githubusercontent.com/assets/330084/24305672/1f66264c-10be-11e7-8af8-16be46d8f8d4.png)

Are you talking about the items on actionToolbar @guyaparker ?

**Comment by guyaparker** [comment]
@pascualin - yes I am talking about the actionToolbar. If you look at http://assets.ctl.io/cyclops/1.8.2/components.html#actionToolbarActiveButton the button with class active doesn't have a style like your screenshot until you hover over it
