### ISSUE TITLE
Button hover feedback removed in latest Cyclops style update 

### ISSUE THREAD

**Issue by guyaparker** [CenturyLinkCloud/Cyclops#134]
Most (if not all) hover styles applied to buttons have been removed in Cyclops 1.8.2 which reduces the feedback to the user. Without that subtle feedback the ability to distinguish some types of active vs. disabled buttons is much harder. Especially outline buttons on certain screens.

**Comment by pascualin** [comment]
Can you advise on this @mattnickles please?

**Comment by mattnickles** [comment]
@guyaparker Thank you Guy. Agree this behavior is not ideal. @pascualin I will put together a spec outlining all the various states and have it for you by tomorrow.

**Comment by pascualin** [comment]
Could you take a look @jsmecham please? I've sent you an email with some designs from @mattnickles
