### ISSUE TITLE
List view item now has hover style

### ISSUE THREAD

**Issue by guyaparker** [CenturyLinkCloud/Cyclops#135]
Cyclops 1.8.2 has added a hover style to items with class list-view-item when previously only list-view-link-item and list-view-editable-item had a hover style.
In a list view where there is a mixture of all three types this is confusing because all lines provide the same user feedback implying that a click will cause an action.

**Comment by pascualin** [comment]
@guyaparker Could you please provide a screenshot for @mattnickles to take a look?

**Comment by guyaparker** [comment]
In both these case my mouse is hovering over the first row (just labelled "Item").

This is from 1.8.2 and has a hover effect:
![screen shot 2017-03-24 at 17 30 46](https://cloud.githubusercontent.com/assets/11406058/24306218/bdbd98d6-10b7-11e7-99ff-b485a75c7a44.png)

This is from 1.7.0 and does not have a hover effect:
![screen shot 2017-03-24 at 17 31 00](https://cloud.githubusercontent.com/assets/11406058/24306227/c7e7f2de-10b7-11e7-8b10-ea92592a3ffb.png)

**Comment by pascualin** [comment]
Could you please take a look at this @jsmecham ?
