### ISSUE TITLE
Cyclops 1.8.3 causes poor alignment of the toolbar search input 

### ISSUE THREAD

**Issue by guyaparker** [CenturyLinkCloud/Cyclops#144]
A change to the padding applied to **html.cyclops .btn** from  "3px 9px 5px" to "6px 10px;" has caused the http://assets.ctl.io/cyclops/1.8.3/listview.html#toolbar search input to no longer align with the buttons:

1.8.2 (See http://assets.ctl.io/cyclops/1.8.2/listview.html#toolbar):
![screen shot 2017-05-10 at 16 33 14](https://cloud.githubusercontent.com/assets/11406058/25907388/3cd5ab2a-359f-11e7-8440-553d05bbe445.png)

1.8.3 (See http://assets.ctl.io/cyclops/1.8.3/listview.html#toolbar):
![screen shot 2017-05-10 at 16 33 29](https://cloud.githubusercontent.com/assets/11406058/25907408/498c6a52-359f-11e7-8640-b66e830b80d0.png)

To correct this I need to add additional CSS:

html.cyclops .search-input svg { top: 10px; }
html.cyclops .search-input input { height: 34px; }

**Comment by pascualin** [comment]
Fixed in v1.8.4
