### ISSUE TITLE
Newbie:  How are Charlist.JS options set ?

### ISSUE THREAD

**Issue by lundstrt** [CenturyLinkCloud/Cyclops#145]
For example, how would we set something like `showLine: false`?

`var options = {
  showLine: false,
  axisX: {
    labelInterpolationFnc: function(value, index) {
      return index % 13 === 0 ? 'W' + value : null;
    }
  }
};`

An example of what I'm trying to implement is here:
[Scatter Chart Example](https://gionkunz.github.io/chartist-js/examples.html#line-scatter-random)

Thanks, Tom

**Comment by guyaparker** [comment]
@lundstrt, if I read you right then I think you would insert the chartist options you want into the chartOptions object that cyclops provides. See http://assets.ctl.io/cyclops/1.8.4/charts.html.

JS:
$('.myChart').chart({type: 'Line', data: data, chartOptions: { showLine: false, axisX: { labelInterpolationFnc: function(value, index) { return index % 13 === 0 ? 'W' + value : null; } } })

Knockout:
<div class="myChart" data-bind="chart:{ type: 'Line', data: data, chartOptions: { showLine: false, axisX: { labelInterpolationFnc: function(value, index) { return index % 13 === 0 ? 'W' + value : null; } } } }"></div>

**Comment by jsmecham** [comment]
What @guyaparker said. Closing.
