### ISSUE TITLE
Inconsistent inverse pageHeader styles

### ISSUE THREAD

**Issue by guyaparker** [CenturyLinkCloud/Cyclops#167]
The user menu in the inverse pageHeader (https://assets.ctl.io/cyclops/1.9.0/navigation.html#pageHeaderInverse) uses hover styles that do not match the menus inserted by GlobalMenus (https://assets.ctl.io/global-menus/2.0.2/examples/all-inverse.html)

![Screenshot 2019-05-27 at 11 13 14](https://user-images.githubusercontent.com/11406058/58543001-78cab800-81f6-11e9-9646-10305cecef8b.png)
![Screenshot 2019-05-27 at 11 13 03](https://user-images.githubusercontent.com/11406058/58543002-79634e80-81f6-11e9-8cf8-35c469c3a695.png)

The normal (not inverse) styles do match.

![Screenshot 2019-05-27 at 11 11 16](https://user-images.githubusercontent.com/11406058/58543032-854f1080-81f6-11e9-9ee9-f1fbe9839a19.png)
![Screenshot 2019-05-27 at 11 11 04](https://user-images.githubusercontent.com/11406058/58543033-854f1080-81f6-11e9-8499-b2ae44d1a199.png)

**Comment by dani-cl-madrid** [comment]
Hi @guyaparker, this has been resolved in the new Cyclops v1.9.1 release and the Global Navigation Menu v2.0.3.

**Comment by guyaparker** [comment]
Great, thank you!
