### ISSUE TITLE
Invisible collapsed navbar toggle on narrow viewports with inverse header

### ISSUE THREAD

**Issue by guyaparker** [CenturyLinkCloud/Cyclops#171]
When the header is inverse and the page is below 991px wide then the collapsed navbar toggle is invisible unless you hover over it. When the header is not inverse then the navbar toggle behaves correctly.
Compare https://assets.ctl.io/cyclops/1.9.3/starterPages/basic-inverse-header.html and https://assets.ctl.io/cyclops/1.9.3/starterPages/basic.html on a narrow viewport.

- Inverse header, not hovering in top right:

![Screenshot 2019-06-13 at 15 53 13](https://user-images.githubusercontent.com/11406058/59494984-3f48ac80-8e86-11e9-9974-0cdc56858421.png)

- Inverse header, and hovering in top right:

![Screenshot 2019-06-13 at 15 52 35](https://user-images.githubusercontent.com/11406058/59494995-4bcd0500-8e86-11e9-957d-2b4d04077b44.png)

- Standard header, not hovering in top right:

![Screenshot 2019-06-13 at 15 52 19](https://user-images.githubusercontent.com/11406058/59495018-5ab3b780-8e86-11e9-845b-6da6472c0dd7.png)

**Comment by dani-cl-madrid** [comment]
Thanks for the report. I'll take a look.
