### ISSUE TITLE
Can you guys provide an edit icon?

### ISSUE THREAD

**Issue by shan-sundaram** [CenturyLinkCloud/Cyclops#18]
We have a use case to edit our templates and was looking for an edit icon. Can you include that in your stack?

**Comment by nathanyoung** [comment]
Typically we use a gear icon + "settings" to represent "editing" the settings of an entity. Is this a situation where this convention can be used?

**Comment by shan-sundaram** [comment]
Our use case is editing an existing playbook template, thought a pencil icon would be appropriate. Your thoughts? Else we can go by your suggestion.

**Comment by osbornm** [comment]
Also in general we tend to stay away from Icon only buttons. Let's chat some about the specific use case. And to be fair I'm not opposed to having one just want to make sure it sticks with the "feel" of the brand/site.

**Comment by shan-sundaram** [comment]
Sure we will discuss during our call today.

**Comment by shan-sundaram** [comment]
Since we decided to go with the gear icon, i am closing this request. Thank you!
