### ISSUE TITLE
Password strength validator and it appears to have a bug in its logic for calculating password strength

### ISSUE THREAD

**Issue by brianwaganer** [CenturyLinkCloud/Cyclops#21]
I’m with RDBS we’re using your password strength validator and it appears to have a bug in its logic for calculating password strength.  We were looking at your calculatePasswordStrength.coffee script and if our password length is over 9 characters and our char types is 3 our strength is 0 which is causing us to fail validation.  When we reduce the password length to exactly nine characters and our char types stays at three we pass validation.

else if password.length <= 9 and charTypes == 3
   strength = 3
should be 
else if password.length >= 9 and charTypes == 3
   strength = 3

**Comment by osbornm** [comment]
fixed a539a9dba8b07c2f30b061cf94a60d4b28b5fa12
