### ISSUE TITLE
Password entry hover-over displays html tags in the message

### ISSUE THREAD

**Issue by brianwaganer** [CenturyLinkCloud/Cyclops#22]
Password entry hover-over displays html tags in the message, like <ul><li>.

<input type="password" class="form-control validationElement" id="database_password" data-bind="value: password, validationElement: password, widget: 'passwordStrength'" title="A password must be at least 9 characters and contain at least 3 of the following: <ul><li>uppercase letters</li><li>lowercase letters</li><li>numbers</li><li>symbols</li></ul>" data-orig-title="">

**Comment by osbornm** [comment]
This is a knockvalidation feature. we recommend that you turn off the insertion of titles `<form class="form-horizontal" data-bind="validationOptions: { insertMessages: false, allowHtmlMessages: true, errorsAsTitle: false }"`

We will update our documentation as needed. Thank you
