### ISSUE TITLE
Slider -> text box not well connected

### ISSUE THREAD

**Issue by steventarver** [CenturyLinkCloud/Cyclops#25]
Examples from rdbs.ctl.io, db details page, resources and alerts pop-in dialogs

- Slider and text box are not live syncing: If I drag the slider, the text is not updated until I release the slider. If I type a value in the text box, the slider is not updated until I tab out of the text box.
- Text box does not obey min/max: I can type any number into the text box. I expect the text values to be bounded by min/max limits. Note: when I tab out of the text box, the value is reset to fall within min/max limits.

Want functionality similar to sliders in https://www.ctl.io/estimator/

**Comment by osbornm** [comment]
The update behavior you are seeing is expected. When you move the slide you see a "preview" of the value as a tooltip and when you let go the value is changed. Updating the textbox as you"type" can lead to problem with validation (i.e 10 is valid so you type 1 and get an error) so this is expected as well and is the built in default behavior of knockout. 

As for your problems with validation we would need more details to debug this, out example page is working correctly see: http://assets.ctl.io/cyclops/1.1.4/forms.html#sliders perhaps something is not wired up as cyclops needs it to be.
