### ISSUE TITLE
Dropdown menu doesn't work in action toolbar confirmation example

### ISSUE THREAD

**Issue by nathanyoung** [CenturyLinkCloud/Cyclops#28]
http://assets.ctl.io/cyclops/1.2.0-rc.1/components.html#actionToolbar

Scroll down to "confirmations"

![screen shot 2016-03-07 at 3 07 32 pm](https://cloud.githubusercontent.com/assets/1447339/13586545/792b7198-e476-11e5-9189-2223c633786b.png)

**Comment by osbornm** [comment]
This is fixed in the final release.
