### ISSUE TITLE
Plain Text in Dropdowns

### ISSUE THREAD

**Issue by osbornm** [CenturyLinkCloud/Cyclops#33]
We don't have any default styles for plain text in dropdowns. An example usage would be to put a phone number in the support dropdown.

**Comment by rathromony** [comment]
Need to review edf135dd0d65c124df7fd8f153c0ad7b56bcbbd1

**Comment by rathromony** [comment]
d82e0bd719ee51633b7482a59bc04c7fa90fa4bd
