### ISSUE TITLE
Need colors for line/area graphs

### ISSUE THREAD

**Issue by bradwilson** [CenturyLinkCloud/Cyclops#39]
You have customized colors for the line graphs, but not for the area beneath them (when enabling area mode), so they just look grey:

<img width="455" alt="screen shot 2016-04-22 at 10 05 57" src="https://cloud.githubusercontent.com/assets/16944/14749024/fcd6c582-0871-11e6-8e20-60b4eecd3af4.png">

I expected the areas to match the line colors.

**Comment by osbornm** [comment]
@nathanyoung you may have already fixed this if so please close this out.

**Comment by osbornm** [comment]
@nathanyoung please review and change if you like

![screen shot 2016-06-09 at 2 32 57 pm](https://cloud.githubusercontent.com/assets/674284/15947209/3b940e4e-2e4f-11e6-98df-e04642d35ebb.png)
