### ISSUE TITLE
Help Wanted: Slider usage

### ISSUE THREAD

**Issue by guyaparker** [CenturyLinkCloud/Cyclops#41]
Not sure if I am missing a detail on the use of the slider control,  is the expectation that the value of the slider is obtained by accessing the input child of the slider?

`<slider id="instances" name="instances" params="value: 1, min: 1, max: 5"></slider>`
...
`$('#instances > input').val();`

The input itself isn't submitted with a normal form submit without some form of processing first, right?

Thanks!

**Comment by osbornm** [comment]
yes we do not name for input of the slider so it would not show up in a standard form post. The expected usage is that you use that you pass the value parameter an observable and that observable will be updated as the value of the slider changes. You can then craft your API post using that value.
