### ISSUE TITLE
overflow menu to large at Certain Browser Widths

### ISSUE THREAD

**Issue by mattskone** [CenturyLinkCloud/Cyclops#43]
Reproduction Steps:
1. Go to a server or group detail page on the platform control app.
2. On the far right of the action bar the settings link should be visible:
![screen shot 2016-05-09 at 2 44 49 pm](https://cloud.githubusercontent.com/assets/2359322/15129144/a15cd986-15f4-11e6-8057-8b597a9bed62.png)
3. Resize the window width to between 1485px and 1400px; the settings link is now hidden:
![screen shot 2016-05-09 at 2 44 34 pm](https://cloud.githubusercontent.com/assets/2359322/15129141/9f43fab2-15f4-11e6-9b8d-6321ae413b10.png)

Expected behavior: Settings link always visible
Actual behavior: Settings link hidden between 1485px and 1400px.

**Comment by turanuk** [comment]
For visibility: Tammy is going to take a look into this for learning how it works -> https://trello.com/c/DVkd6CRx/588-cyclops-bug-investigation-https-github-com-centurylinkcloud-cyclops-issues-43

**Comment by osbornm** [comment]
This seem to be getting hit more often... 

https://t3n.zendesk.com/agent/tickets/1304204

**Comment by turanuk** [comment]
Another internal ticket: https://t3n.zendesk.com/agent/tickets/1303632

**Comment by osbornm** [comment]
This seems to only happen when there is a right toolbar.

**Comment by nathanyoung** [comment]
fixed via https://github.com/CenturyLinkCloud/Cyclops/commit/88106622cab90fe09e2186bbddc1023fde6f091f.

Released in 1.6
