### ISSUE TITLE
Internationalization/Globalization

### ISSUE THREAD

**Issue by guyaparker** [CenturyLinkCloud/Cyclops#44]
What is the roadmap for internationalization/globalization in Cyclops?
Today I would have to duplicate and localize cyclops.tmpl.html, among other things, in order to support non-English user interfaces. As a one time task that would be manageable but will quickly become unmanageable as new versions are released and the templates change over time.
Does CLC support anything other than English that would drive improvement to this area of Cyclops?

**Comment by osbornm** [comment]
There is no plans to support anything other than english in the CLC control portal so it is unlikely that cyclops will support anything other than english. However, it is an open source project and we would be willing to add it if "the right" implementation was submitted. 

I'm going to close this issue out but if someone wants to take a stab and adding support to cyclops lets reopen it and have an implementation discussion so no one waste time.
