### ISSUE TITLE
Inline confirm on a btn-sm button will generate a Yes and a No button of different sizes

### ISSUE THREAD

**Issue by guyaparker** [CenturyLinkCloud/Cyclops#48]
The inline confirm widget will generate a Yes and a No button of different sizes if it is used on a button with a btn-sm class.
The Yes button correctly keeps the btn-sm class but the No button displays at the default (larger) size.

**Comment by osbornm** [comment]
We may have to special case "size" classes or allow you to pass in classes for the no button. The yes button works by coping all the styles from original button. We wouldn't want to do this for no because we don't want to copy things like `btn-danger` etc.
