### ISSUE TITLE
Help Wanted: dynamically loaded navLocal collapsed into a stacked menu not working

### ISSUE THREAD

**Issue by guyaparker** [CenturyLinkCloud/Cyclops#49]
I have a page that loads a navLocal element via ajax. When the page width is narrow navLocal correctly collapses into a stacked menu but it does not expand when clicked.
I am guessing I need to manually add something because the nav element was not present when cyclops loaded but I can't quite figure it out.
Thanks!

**Comment by guyaparker** [comment]
I should say that if I run a test where the navLocal is present in the base page (and not loaded via ajax) then everything works just as I expect

**Comment by guyaparker** [comment]
The best I can come up with is to copy this from cyclops.js and add it into the ajax response containing the navLocal element:

`  $(function() {
    var navbars, setAriaAndClass, toggle;
    toggle = function() {
      var btn, menu;
      btn = $(this);
      menu = btn.parents('.navbar').find('.navbar-collapse');
      if (menu.is(':visible')) {
        menu.stop().slideUp(300, function() {
          return setAriaAndClass(menu, btn);
        });
      } else {
        menu.stop().slideDown(300, function() {
          return setAriaAndClass(menu, btn);
        });
      }
    };
    setAriaAndClass = function(menu, btn) {
      var isVisible;
      isVisible = menu.is(':visible');
      menu.attr('aria-expanded', isVisible);
      btn.attr('aria-expanded', isVisible);
      if (isVisible) {
        menu.removeClass('collapsed');
        btn.addClass('open');
      } else {
        menu.addClass('collapsed');
        btn.removeClass('open');
      }
    };
    return navbars = $("nav.navbar-local").each(function(idx, nb) {
      var $nb, btn, menu;
      $nb = $(nb);
      menu = $nb.find('.navbar-collapse');
      btn = $nb.find('.navbar-toggle');
      setAriaAndClass(menu, btn);
      return btn.click(toggle);
    });
  });`

**Comment by osbornm** [comment]
Yes you are correct we, we run some code at startup (https://github.com/CenturyLinkCloud/Cyclops/blob/master/src/scripts/navbar.coffee) that finds these and add the appropriate click events. 

We've never had a case where navigation was loaded via AJAX in our designs it's normally already on the page at render time.

**Comment by osbornm** [comment]
We can consider having a widget that would wire this behavior up something like `widget: 'navbar' `.

**Comment by guyaparker** [comment]
Thanks, would be worthwhile to consider. Or so something like dropdown() that is used for when page header navigation dropdowns load after cyclops. I can work around it too. In the context of something familiar to you we have a pane tree view loading pages which potentially contain a localNav element appropriate for the page. Can show you if necessary
