### ISSUE TITLE
Main-nav loading state

### ISSUE THREAD

**Issue by osbornm** [CenturyLinkCloud/Cyclops#51]
looks like we need to wrap the word fetching in a `main-nav-label` span? 
![screen shot 2016-06-29 at 9 53 55 am](https://cloud.githubusercontent.com/assets/674284/16456972/82910e06-3ddf-11e6-9d0a-24509010b6c5.png)

**Comment by osbornm** [comment]
This also effects the failed state.

**Comment by nathanyoung** [comment]
look at failed state too
