### ISSUE TITLE
Navigation Update

### ISSUE THREAD

**Issue by guyaparker** [CenturyLinkCloud/Cyclops#55]
Is the new navigation described at "https://www.ctl.io/knowledge-base/general/control-portal-navigation-update/" going to be included in Cyclops so other services can match the style?
If yes, is there an estimated timeline so other groups can plan development cycles?
Thanks!

**Comment by osbornm** [comment]
Yes, the base control that drives the menu is in 1.4.0 (undocumented) and will be fully documented in 1.5.0. However the data APIs that allow sat apps to all have the same set of menus will be made available in the July 19th release of Platform. 

Additionally we have an AWESOME (yes i'm tooting my own horn) implementation story for teams that we will be showing off that day at OPV. If you'd like more information message me in slack.
