### ISSUE TITLE
JS error when Cyclops tmpl file has not loaded

### ISSUE THREAD

**Issue by guyaparker** [CenturyLinkCloud/Cyclops#62]
I have noticed intermittent issues (often when refreshing a page) where a JS error occurs because the cyclops tmpl has not yet loaded. So somehow the $.holdReady(true); set whilst the tmpl file loads is not preventing the view models from binding.

> Error: Unable to process binding "component: function (){return l}" Message: Component 'pane': Cannot find element with ID cyclops.pane

Has anyone else seen this and figured out a solution?

My workaround is based on: http://swizec.com/blog/how-to-properly-wait-for-dom-elements-to-show-up-in-modern-browsers/swizec/6663

**Comment by osbornm** [comment]
I know this is a silly question but just checking is everything inside a jquery document ready function? can you double check?

**Comment by osbornm** [comment]
Also if you have a constant way to reproduce this that would be help I have never seen this...

**Comment by guyaparker** [comment]
Not a silly question and yes. But I'll triple check that some third party code is not doing anything weird that is hard to spot. I'll also try to come up with a reproducible test case. Knowing that you have not seen it makes me think there is something else going on.
Thanks

**Comment by osbornm** [comment]
I'm going to close this for now but If you see it again and or get a good repro please reopen.
