### ISSUE TITLE
Any plans to allow pane element to be collapsed?

### ISSUE THREAD

**Issue by guyaparker** [CenturyLinkCloud/Cyclops#63]
So one feature that no longer exists in the CLC UI since the update earlier this week is the ability to collapse the pane that contains the list of servers on the left.

Are there any plans to add this into Cyclops so that the user can temporarily maximize screen real estate for the main content area? Sometimes the pane area can just be, well, a pain :-)

**Comment by osbornm** [comment]
In our experience little to no one ever collapsed it manual. We have styles in place to collapse it on smaller screens... 

<img width="704" alt="screen shot 2016-07-21 at 9 43 52 am" src="https://cloud.githubusercontent.com/assets/674284/17026995/acb8b586-4f27-11e6-8ffc-932497f788b9.png">
