### ISSUE TITLE
Long allert banner text can appear behind the main-nav

### ISSUE THREAD

**Issue by guyaparker** [CenturyLinkCloud/Cyclops#67]
If I understand that the correct placement of an alert banner is immediately after nav then if the alert banner contains long text depending on the screen width and display of main-nav and pane then the text can appear "behind" the main-nav and pane.
Should some additional media-width padding be applied to avoid this?
Or should the alert banner be inside main ?

**Comment by osbornm** [comment]
The alert banner should be inside of the `main` tag. @nathanyoung correct me if I'm wrong...

**Comment by guyaparker** [comment]
Yeah, it seems to behave much better there. So I think the current documentation just needs a tweak:

> Alert banners should be used for portal or service wide notifications, and should appear immediately following the page header navigation.

**Comment by osbornm** [comment]
Moved to #68
