### ISSUE TITLE
Brand Bar background color visible with custom Nav color

### ISSUE THREAD

**Issue by troyschneringer** [CenturyLinkCloud/Cyclops#77]
This is apparent especially when you choose the Nav color to be white as there is a thin black line across the bottom.

![screen shot 2016-08-24 at 2 48 41 pm](https://cloud.githubusercontent.com/assets/1273031/17949374/dfc47ad0-6a09-11e6-960c-ef1ef1e895c1.png)

**Comment by nathanyoung** [comment]
Fix for this is implemented in the T3 project. The default color is overwritten via the custom branded css that's passed down via platform. 

https://github.com/Tier3/T3/commit/342b91d43fe67fc05b60dadf7fc0e8fd21851248

fyi: @osbornm
